# Basic docker-compose to run rundeck, mariadb, and nginx
# Modify to suit your environment
# Use of secrets file is highly recommended
# MYSQL_ROOT_PASSWORD and DATABASE_ADMIN_PASSWORD need to be the same value
# Add volumes to mariadb and rundeck sections to maintain persistence

version: '3'

services:
    mariadb:
        image: mariadb:10.5.8
        container_name: mariadb
        restart: on-failure:5
        environment:
            MYSQL_ROOT_PASSWORD: "gnregiragrbgaugfr623213"
        volumes:
            - mysqldata=/var/lib/mysql

    rundeck:
        #image: ${RUNDECK_IMAGE:-jordan/rundeck:latest}
        container_name: rundeck
        build: .
        links:
            - mariadb
        depends_on:
            - mariadb
        restart: on-failure:5
        environment:
            EXTERNAL_SERVER_URL: "http://10.109.255.16:4440/rundeck"
            SERVER_URL: ${EXTERNAL_SERVER_URL}
            RDECK_JVM_OPTS: "-Drundeck.jetty.connector.forwarded=true -Dserver.servlet.context-path=/rundeck"
            NO_LOCAL_MYSQL: "true"
            RUNDECK_STORAGE_PROVIDER: "db"
            RUNDECK_PROJECT_STORAGE_TYPE: "db"
            DATABASE_URL: "jdbc:mysql://mariadb/rundeckdb?autoReconnect=true"
            DATABASE_ADMIN_USER: "root"
            DATABASE_ADMIN_PASSWORD: "gnregiragrbgaugfr623213"
            RUNDECK_PASSWORD: "!Cadorna2021"
        ports:
            - 4440:4440

    nginx:
        image: nginx:latest
        container_name: nginx
        links:
            - rundeck
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - rundeck
        restart: on-failure:5
        ports:
            - 80:80
            - 443:443
volumes:
  mysqldata: